export const LEVEL_COLORS = { beginner: "#4ca86a", intermediate: "#c9a84c", advanced: "#c94c4c" };
export const LEVEL_ORDER = { beginner: 0, intermediate: 1, advanced: 2 };

const EVENTS = {
  he: [
    { id:"egypt", name:"מצרים העתיקה", year:'3100–30 לפנה"ס', era:"עולם עתיק", tags:["civilization","africa"], level:"beginner", desc:'אחת הציביליזציות הגדולות בהיסטוריה, שנשלטה על ידי פרעונים לאורך 3,000 שנה. המצרים בנו פירמידות, פיתחו כתב היפרוגליפי ויצרו מערכת ממשל מורכבת.', quick:['נשלטה על ידי פרעונים לאורך 3,000 שנה','בנו פירמידות ופיתחו כתב היפרוגליפי','נכבשה על ידי רומא ב-30 לפנה"ס'] },
    { id:"greece", name:"יוון הקלאסית", year:'500–323 לפנה"ס', era:"עולם עתיק", tags:["civilization","europe"], level:"beginner", desc:"תקופת הזוהר של אתונה. כאן נולדה הדמוקרטיה, הפילוסופיה, הדרמה והאולימפיאדה.", quick:["כאן נולדה הדמוקרטיה","סוקרטס, אפלטון, אריסטו","השפיעה על כל תרבות מערבית"] },
    { id:"rome", name:"האימפריה הרומית", year:'27 לפנה"ס – 476 לספירה', era:"עולם עתיק", tags:["civilization","europe"], level:"beginner", desc:'אחת האימפריות הגדולות בהיסטוריה. בשיאה שלטה על 70 מיליון איש מבריטניה ועד מסופוטמיה.', quick:["שלטה על רוב העולם הידוע","הניחה יסודות למשפט ושפה מערבית","נפלה ב-476 לספירה"] },
    { id:"alexander", name:"אלכסנדר הגדול", year:'336–323 לפנה"ס', era:"עולם עתיק", tags:["war","politics"], level:"intermediate", desc:"מלך מוקדוניה שכבש אימפריה מיוון ועד הודו בתוך 13 שנה. מסעותיו הפיצו תרבות יוונית.", quick:['כבש ממוקדוניה ועד הודו','הפיץ תרבות יוונית','מת בגיל 32'] },
    { id:"islam", name:"עלייתה של האסלאם", year:"610–750", era:"ימי הביניים", tags:["religion","middle east"], level:"beginner", desc:"מוחמד ייסד את הדת האסלאמית בשנת 610. תוך מאה שנה פשטה מספרד ועד פרס.", quick:["ייסוד האסלאם ב-610","התפשטות מספרד ועד פרס","שמרה על ידע מדעי קדום"] },
    { id:"crusades", name:"מסעי הצלב", year:"1096–1291", era:"ימי הביניים", tags:["war","religion","middle east"], level:"intermediate", desc:"מסעות צבאיים לכיבוש ארץ הקודש. הותירו צלקות ביחסים בין דתות.", quick:["8 מסעות עיקריים","ירושלים נכבשה ואבדה","עיצבו יחסים נוצרים-מוסלמים לדורות"] },
    { id:"blackdeath", name:"המוות השחור", year:"1347–1351", era:"ימי הביניים", tags:["science","europe"], level:"beginner", desc:"מגיפת הדבר הקשה ביותר בהיסטוריה — הרגה שליש מאוכלוסיית אירופה.", quick:["הרגה שליש מאירופה","שינתה כלכלה וחברה","האיצה את סוף ימי הביניים"] },
    { id:"french_rev", name:"המהפכה הצרפתית", year:"1789–1799", era:"המאה ה-18", tags:["revolution","europe","politics"], level:"beginner", desc:"תקופה שהפילה את המלוכה, כוננה רפובליקה, והסתיימה בעלייתו של נפוליאון.", quick:["הפילה את המלוכה","הפיצה חירות, שוויון ואחווה","הובילה לנפוליאון"] },
    { id:"napoleon", name:"נפוליאון ואירופה", year:"1799–1815", era:"המאה ה-19", tags:["war","europe","politics"], level:"intermediate", desc:"נפוליאון בונפרטה כבש את רוב אירופה והפיץ את ערכי המהפכה.", quick:["כבש את רוב אירופה","הפיץ קוד משפטי","הובס בוואטרלו ב-1815"] },
    { id:"industrial", name:"המהפכה התעשייתית", year:"1760–1840", era:"המאה ה-19", tags:["science","global"], level:"beginner", desc:"המעבר מייצור ידני לממוכן. הקיטור, הרכבת, בתי החרושת שינו את אופן החיים.", quick:["החלה בבריטניה","מנוע הקיטור שינה הכל","יצרה את המעמד הפועל"] },
    { id:"ww1", name:"מלחמת העולם הראשונה", year:"1914–1918", era:"המאה ה-20", tags:["war","europe","global"], level:"beginner", desc:"המלחמה הגדולה — סיימה ארבע אימפריות ושתלה זרעים למלחמת העולם השנייה.", quick:["הופעלה ע\"י רצח פרדיננד","ארבע אימפריות קרסו","הסכם ורסאי שתל זרעים למלה\"ע 2"] },
    { id:"holocaust", name:"השואה", year:"1941–1945", era:"המאה ה-20", tags:["war","europe","genocide"], level:"beginner", desc:"הרצח השיטתי של שישה מיליון יהודים על ידי המשטר הנאצי.", quick:["שישה מיליון יהודים נרצחו","מחנות ריכוז ומוות","הובילה לאו\"ם ולזכויות אדם"] },
    { id:"ww2", name:"מלחמת העולם השנייה", year:"1939–1945", era:"המאה ה-20", tags:["war","europe","global"], level:"beginner", desc:"הסכסוך הקטלני ביותר בהיסטוריה — 70–85 מיליון הרוגים.", quick:["70–85 מיליון הרוגים","גרמניה הנאצית נגד בעלות-הברית","הסתיים ב-1945"] },
    { id:"dday", name:'מבצע נורמנדי (D-Day)', year:"6 ביוני 1944", era:"המאה ה-20", tags:["war","europe"], level:"intermediate", desc:"156,000 חיילים פלשו לחופי נורמנדי — הפלישה הגדולה ביותר בהיסטוריה.", quick:["156,000 חיילים ב-5 חופים","פתח חזית מערבית","נחשב לנקודת המפנה של מלה\"ע 2"] },
    { id:"israel", name:"הקמת מדינת ישראל", year:"1948", era:"המאה ה-20", tags:["politics","middle east"], level:"beginner", desc:"ב-14 במאי 1948 הכריז דוד בן-גוריון על הקמת מדינת ישראל.", quick:["הוכרזה ב-14 במאי 1948","קשורה לשואה ולציונות","גררה מלחמת עצמאות"] },
    { id:"coldwar", name:"המלחמה הקרה", year:"1947–1991", era:"המאה ה-20", tags:["politics","war","global"], level:"beginner", desc:'מאבק גיאופוליטי בין ארה"ב לברה"מ — מרוץ גרעיני, מרוץ חלל, מלחמות פרוקסי.', quick:['ארה"ב נגד ברה"מ','מלחמות פרוקסי בקוריאה ווייטנאם','הסתיים עם פירוק ברה"מ'] },
    { id:"moonlanding", name:"נחיתה על הירח", year:"1969", era:"המאה ה-20", tags:["science","global"], level:"beginner", desc:"ב-20 ביולי 1969 ניל ארמסטרונג הפך לאדם הראשון על הירח.", quick:["ניל ארמסטרונג — ראשון על הירח",'ניצחון ארה"ב במרוץ החלל',"600 מיליון צפו בשידור חי"] },
    { id:"berlin_wall", name:"נפילת חומת ברלין", year:"1989", era:"המאה ה-20", tags:["revolution","politics","europe"], level:"beginner", desc:"ב-9 בנובמבר 1989 נפלה חומת ברלין — סמל לקץ המלחמה הקרה.", quick:["עמדה 28 שנה","סמל לקץ המלחמה הקרה","הובילה לאיחוד גרמניה"] },
    { id:"ussr_collapse", name:"קריסת ברית המועצות", year:"1991", era:"המאה ה-20", tags:["revolution","politics","global"], level:"intermediate", desc:'פירוק ברה"מ ב-25 בדצמבר 1991 — 15 מדינות עצמאיות וקץ המלחמה הקרה.', quick:["15 מדינות חדשות קמו","סיים את עידן המלחמה הקרה","משבר כלכלי ורפורמות גורבצ'וב"] },
    { id:"nelson_mandela", name:"נלסון מנדלה וסיום האפרטהייד", year:"1990–1994", era:"המאה ה-20", tags:["politics","revolution","africa"], level:"beginner", desc:"לאחר 27 שנות כלא, מנדלה הוביל את דרום אפריקה לדמוקרטיה ב-1994.", quick:["27 שנות כלא","הוביל מעבר לדמוקרטיה","נבחר לנשיא ב-1994"] },
  ],
  en: [
    { id:"egypt", name:"Ancient Egypt", year:"3100–30 BC", era:"Ancient World", tags:["civilization","africa"], level:"beginner", desc:"One of the greatest civilizations in history, ruled by pharaohs for over 3,000 years. Egyptians built the pyramids and developed hieroglyphic writing.", quick:["Ruled by pharaohs for 3,000 years","Built pyramids and hieroglyphic writing","Conquered by Rome in 30 BC"] },
    { id:"greece", name:"Classical Greece", year:"500–323 BC", era:"Ancient World", tags:["civilization","europe"], level:"beginner", desc:"The golden age of Athens. Democracy, philosophy, drama and the Olympics were born here.", quick:["Birthplace of democracy","Socrates, Plato, Aristotle","Immeasurable influence on Western civilization"] },
    { id:"rome", name:"The Roman Empire", year:"27 BC – 476 AD", era:"Ancient World", tags:["civilization","europe"], level:"beginner", desc:"One of history's greatest empires, ruling 70 million people from Britain to Mesopotamia at its peak.", quick:["Ruled most of the known world","Laid foundations for law and Western culture","Fell in 476 AD"] },
    { id:"alexander", name:"Alexander the Great", year:"336–323 BC", era:"Ancient World", tags:["war","politics"], level:"intermediate", desc:"King of Macedon who conquered an empire from Greece to India in just 13 years, spreading Hellenistic culture.", quick:["Conquered from Macedonia to India","Spread Greek culture","Died at 32"] },
    { id:"islam", name:"Rise of Islam", year:"610–750 AD", era:"Middle Ages", tags:["religion","middle east"], level:"beginner", desc:"Muhammad founded Islam in 610 AD. Within a century the faith spread from Spain to Persia.", quick:["Islam founded in 610 AD","Spread from Spain to Persia","Preserved ancient scientific knowledge"] },
    { id:"crusades", name:"The Crusades", year:"1096–1291", era:"Middle Ages", tags:["war","religion","middle east"], level:"intermediate", desc:"Military expeditions to recapture the Holy Land. Left deep scars on religious relations.", quick:["8 major Crusades","Jerusalem captured and lost multiple times","Shaped Christian-Muslim relations for centuries"] },
    { id:"blackdeath", name:"The Black Death", year:"1347–1351", era:"Middle Ages", tags:["science","europe"], level:"beginner", desc:"The deadliest pandemic in history, killing a third of Europe — about 25 million people.", quick:["Killed a third of Europe","Transformed economics and society","Accelerated the end of the Middle Ages"] },
    { id:"french_rev", name:"French Revolution", year:"1789–1799", era:"18th Century", tags:["revolution","europe","politics"], level:"beginner", desc:"Radical transformation that overthrew the monarchy, established a republic, and ended with Napoleon's rise.", quick:["Overthrew the monarchy","Spread liberty, equality, fraternity","Led to Napoleon"] },
    { id:"napoleon", name:"Napoleon and Europe", year:"1799–1815", era:"19th Century", tags:["war","europe","politics"], level:"intermediate", desc:"Napoleon Bonaparte conquered most of Europe and spread the values of the French Revolution.", quick:["Conquered most of Europe","Spread legal code still in use","Defeated at Waterloo 1815"] },
    { id:"industrial", name:"Industrial Revolution", year:"1760–1840", era:"19th Century", tags:["science","global"], level:"beginner", desc:"The shift from manual to mechanized production. Steam, railways, factories changed everything.", quick:["Began in Britain","Steam engines transformed production","Created the working class"] },
    { id:"ww1", name:"World War I", year:"1914–1918", era:"20th Century", tags:["war","europe","global"], level:"beginner", desc:"The Great War ended four empires and planted seeds for WWII through the Treaty of Versailles.", quick:["Triggered by Franz Ferdinand's assassination","Four empires collapsed","Treaty of Versailles planted WWII seeds"] },
    { id:"holocaust", name:"The Holocaust", year:"1941–1945", era:"20th Century", tags:["war","europe","genocide"], level:"beginner", desc:"The systematic murder of six million Jews by the Nazi regime.", quick:["Six million Jews murdered","Concentration and death camps","Led to the UN and human rights framework"] },
    { id:"ww2", name:"World War II", year:"1939–1945", era:"20th Century", tags:["war","europe","global"], level:"beginner", desc:"The deadliest conflict in history — 70–85 million deaths. Nazi Germany vs the Allied powers.", quick:["70–85 million deaths","Nazi Germany vs Allied powers","Ended in 1945"] },
    { id:"dday", name:"D-Day: Normandy Invasion", year:"June 6, 1944", era:"20th Century", tags:["war","europe"], level:"intermediate", desc:"The largest seaborne invasion: 156,000 Allied troops stormed Normandy beaches, opening the Western Front.", quick:["156,000 troops on 5 beaches","Opened the Western Front","Turning point of WWII in Europe"] },
    { id:"israel", name:"Establishment of Israel", year:"1948", era:"20th Century", tags:["politics","middle east"], level:"beginner", desc:"On May 14, 1948, David Ben-Gurion proclaimed the State of Israel.", quick:["Declared May 14, 1948","Connected to Holocaust and Zionism","Immediately triggered war"] },
    { id:"coldwar", name:"The Cold War", year:"1947–1991", era:"20th Century", tags:["politics","war","global"], level:"beginner", desc:"Geopolitical struggle between USA and USSR — nuclear arms race, space race, proxy wars.", quick:["USA vs. USSR","Proxy wars in Korea and Vietnam","Ended with Soviet collapse"] },
    { id:"moonlanding", name:"Moon Landing", year:"1969", era:"20th Century", tags:["science","global"], level:"beginner", desc:"On July 20, 1969, Neil Armstrong became the first human to walk on the Moon.", quick:["Neil Armstrong — first on the Moon","US victory in the Space Race","600 million watched live"] },
    { id:"berlin_wall", name:"Fall of the Berlin Wall", year:"1989", era:"20th Century", tags:["revolution","politics","europe"], level:"beginner", desc:"On November 9, 1989, the Berlin Wall fell after 28 years — symbol of the Cold War's end.", quick:["Stood for 28 years","Symbol of Cold War's end","Led to German reunification"] },
    { id:"ussr_collapse", name:"Collapse of Soviet Union", year:"1991", era:"20th Century", tags:["revolution","politics","global"], level:"intermediate", desc:"The USSR dissolved on December 25, 1991 — 15 independent republics and end of the Cold War.", quick:["15 new nations emerged","Ended the Cold War era","Economic crisis and Gorbachev's reforms"] },
    { id:"nelson_mandela", name:"Nelson Mandela & End of Apartheid", year:"1990–1994", era:"20th Century", tags:["politics","revolution","africa"], level:"beginner", desc:"After 27 years in prison, Mandela led South Africa to multiracial democracy in 1994.", quick:["27 years in prison","Led transition to democracy","Elected President in 1994"] },
  ]
};

export default EVENTS;
